services:
    fantasy-baseball-app:
        container_name: fantasy-baseball-app-bm
        build:
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:5005:5005
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005